coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        flags:
          - unit
          - application

ignore:
  - "applicationtest"
  - "store/migrations"
  - "server/swaggerui"
  - "target"
  - "telemetry"
